name: Rust CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        components: clippy
        override: true

    - name: Run Clippy (Linting)
      run: cargo clippy -- -D warnings

    - name: Build Release Binary
      run: cargo build --release

    - name: Run Tests
      run: cargo test

    - name: Upload Binary Artifact
      uses: actions/upload-artifact@v3
      with:
        name: individual2
        path: ./target/release/individual2
